### ISSUE TITLE
Project is not running in xcoe

### ISSUE THREAD

**Issue by elsadeny** [eycorsican/ileaf#1]
The project is still not running, how can I fix it.

![image](https://user-images.githubusercontent.com/29357454/97798031-4fb91d00-1c5d-11eb-9601-4f78ce50bf4e.png)

**Comment by itsjohnye** [comment]
try to chang your _Header Search Paths_ in _Build settings_

**Comment by elsadeny** [comment]
is there anything am doing wrong? The error says undefined symbol: _run_leaf 
please help!!


Showing Recent Messages
Ld /Users/apple/Library/Developer/Xcode/DerivedData/iLeaf-dworleaopdxwlnfwglqkfofetcrd/Build/Products/Debug-iphonesimulator/PacketTunnel.appex/PacketTunnel normal x86_64 (in target 'PacketTunnel' from project 'iLeaf')
    cd /Users/apple/Documents/xgo/ileaf
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios12.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.7.sdk -L/Users/apple/Library/Developer/Xcode/DerivedData/iLeaf-dworleaopdxwlnfwglqkfofetcrd/Build/Products/Debug-iphonesimulator -L/Users/apple/Documents/xgo/ileaf/PacketTunnel/libleaf -F/Users/apple/Library/Developer/Xcode/DerivedData/iLeaf-dworleaopdxwlnfwglqkfofetcrd/Build/Products/Debug-iphonesimulator -F/Users/apple/Documents/xgo/ileaf/PacketTunnel -filelist /Users/apple/Library/Developer/Xcode/DerivedData/iLeaf-dworleaopdxwlnfwglqkfofetcrd/Build/Intermediates.noindex/iLeaf.build/Debug-iphonesimulator/PacketTunnel.build/Objects-normal/x86_64/PacketTunnel.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/../../Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/apple/Library/Developer/Xcode/DerivedData/iLeaf-dworleaopdxwlnfwglqkfofetcrd/Build/Intermediates.noindex/iLeaf.build/Debug-iphonesimulator/PacketTunnel.build/Objects-normal/x86_64/PacketTunnel_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fapplication-extension -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/apple/Library/Developer/Xcode/DerivedData/iLeaf-dworleaopdxwlnfwglqkfofetcrd/Build/Intermediates.noindex/iLeaf.build/Debug-iphonesimulator/PacketTunnel.build/Objects-normal/x86_64/PacketTunnel.swiftmodule -e _NSExtensionMain -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/apple/Library/Developer/Xcode/DerivedData/iLeaf-dworleaopdxwlnfwglqkfofetcrd/Build/Intermediates.noindex/iLeaf.build/Debug-iphonesimulator/PacketTunnel.build/PacketTunnel.appex-Simulated.xcent -framework NetworkExtension -lleaf -Xlinker -dependency_info -Xlinker /Users/apple/Library/Developer/Xcode/DerivedData/iLeaf-dworleaopdxwlnfwglqkfofetcrd/Build/Intermediates.noindex/iLeaf.build/Debug-iphonesimulator/PacketTunnel.build/Objects-normal/x86_64/PacketTunnel_dependency_info.dat -o /Users/apple/Library/Developer/Xcode/DerivedData/iLeaf-dworleaopdxwlnfwglqkfofetcrd/Build/Products/Debug-iphonesimulator/PacketTunnel.appex/PacketTunnel

ld: warning: ignoring file /Users/apple/Documents/xgo/ileaf/PacketTunnel/libleaf/libleaf.a, missing required architecture x86_64 in file /Users/apple/Documents/xgo/ileaf/PacketTunnel/libleaf/libleaf.a (1 slices)
Undefined symbols for architecture x86_64:
  "_run_leaf", referenced from:
      closure #1 () -> () in closure #1 (Swift.Error?) -> () in PacketTunnel.PacketTunnelProvider.startTunnel(options: [Swift.String : __C.NSObject]?, completionHandler: (Swift.Error?) -> ()) -> () in PacketTunnelProvider.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by eycorsican** [comment]
The released leaf library [supports only aarch64 targets](https://github.com/eycorsican/leaf/blob/6a82ee9b89cb19e5ee871667fd1480f60b5b80ff/Makefile#L2), that said, it can only run on a real device. Though you can compile a x86_64 version manually.
