### ISSUE TITLE
From JSON to the conf

### ISSUE THREAD

**Issue by elsadeny** [eycorsican/ileaf#10]
Is there a way I can configure this json from our server to the app? @eycorsican 
I tried everything but didn't work.

{
    "log": {
        "access": "",
        "error": "",
        "loglevel": "error"
    },
    "inbounds": [
        {
            "tag": "socks-in",
            "port": 1080,
            "listen": "::",
            "protocol": "socks",
            "settings": {
                "auth": "noauth",
                "udp": true,
                "ip": "127.0.0.1"
            }
        },
        {
            "tag": "http-in",
            "port": 8123,
            "listen": "::",
            "protocol": "http"
        }
    ],
    "outbounds": [
        {
            "protocol": "vmess",
            "settings": {
                "vnext": [
                    {
                        "address": "hk4.agakoti2.com",
                        "port": 80,
                        "users": [
                            {
                                "email": "user@v2ray.com",
                                "id": "568fa5f1-db6a-3915-90ef-8befe874b671",
                                "alterId": 2,
                                "security": "auto"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "ws",
                "wsSettings": {
                    "connectionReuse": true,
                    "path": "/hls/cctv5phd.m3u8",
                    "headers": {
                        "Host": "ajax.microsoft.com"
                    }
                }
            },
            "mux": {
                "enabled": true
            },
            "tag": "proxy"
        },
        {
            "protocol": "freedom",
            "tag": "direct",
            "settings": {
                "domainStrategy": "UseIP"
            }
        }
    ],
    "dns": {
        "servers": [
            "1.0.0.1",
            "localhost"
        ]
    },
    "routing": {
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "type": "field",
                "ip": [
                    "geoip:private",
                    "geoip:cn"
                ],
                "outboundTag": "direct"
            },
            {
                "type": "field",
                "domain": [
                    "geosite:cn"
                ],
                "outboundTag": "direct"
            }
        ]
    }
}%

**Comment by eycorsican** [comment]
This is obviously not a valid config for Leaf.
