### ISSUE TITLE
大神您好，我按照咱们的这个代码配置了之后，ip并没有发生变化，希望能得到您的帮助，谢谢

### ISSUE THREAD

**Issue by ChenMoGe2** [eycorsican/ileaf#11]
`import NetworkExtension

let appGroup = "group.xxx.xxx.xxx"

let conf = """
[General]
loglevel = info
dns-server = 114.114.114.114, 223.5.5.5
tun-fd = REPLACE-ME-WITH-THE-FD

[Proxy]
Direct = direct
Reject = reject
SS = ss, xxxx, xxxx, encrypt-method=aes-256-gcm, password=xxxx

[Rule]
Final, SS
"""

class PacketTunnelProvider: NEPacketTunnelProvider {
    override func startTunnel(options: [String : NSObject]?, completionHandler: @escaping (Error?) -> Void) {
        let tunnelNetworkSettings = createTunnelSettings()
        setTunnelNetworkSettings(tunnelNetworkSettings) { [weak self] error in
            let tunFd = self?.packetFlow.value(forKeyPath: "socket.fileDescriptor") as! Int32
            let confWithFd = conf.replacingOccurrences(of: "REPLACE-ME-WITH-THE-FD", with: String(tunFd))
            let url = FileManager().containerURL(forSecurityApplicationGroupIdentifier: appGroup)!.appendingPathComponent("running_config.conf")
            do {
                try confWithFd.write(to: url, atomically: false, encoding: .utf8)
            } catch {
                NSLog("fialed to write config file \(error)")
            }
            let path = url.absoluteString
            let start = path.index(path.startIndex, offsetBy: 7)
            let subpath = path[start..<path.endIndex]
            DispatchQueue.global(qos: .userInteractive).async {
                signal(SIGPIPE, SIG_IGN)
                run_leaf(String(subpath))
            }
            completionHandler(nil)
        }
    }
    
    override func stopTunnel(with reason: NEProviderStopReason, completionHandler: @escaping () -> Void) {
        completionHandler()
    }
    
    override func handleAppMessage(_ messageData: Data, completionHandler: ((Data?) -> Void)?) {
        // Add code here to handle the message.
        if let handler = completionHandler {
            handler(messageData)
        }
    }
    
    override func sleep(completionHandler: @escaping () -> Void) {
        // Add code here to get ready to sleep.
        completionHandler()
    }
    
    override func wake() {
        // Add code here to wake up.
    }
    
    func createTunnelSettings() -> NEPacketTunnelNetworkSettings  {
        let newSettings = NEPacketTunnelNetworkSettings(tunnelRemoteAddress: "240.0.0.10")
        newSettings.ipv4Settings = NEIPv4Settings(addresses: ["240.0.0.1"], subnetMasks: ["255.255.255.0"])
        newSettings.ipv4Settings?.includedRoutes = [NEIPv4Route.`default`()]
        newSettings.proxySettings = nil
        newSettings.dnsSettings = NEDNSSettings(servers: ["223.5.5.5", "8.8.8.8"])
        newSettings.mtu = 1500
        return newSettings
    }
}
`

appGroup这里我修改了，我使用以上代码连接代理后，百度搜索ip并没有变化，使用我自己开发的tcp和udp测试demo在服务器上读取ip也没有变化，请问是我哪里配置错误了吗，麻烦大神能指教，谢谢！

**Comment by ChenMoGe2** [comment]
补充下，我是在IOS14下运行的，不知是不是和版本有关

**Comment by eycorsican** [comment]
```
FINAL, SS
```

全大写

**Comment by ChenMoGe2** [comment]
谢谢您！确实是大小写的问题，然后又遇到了另外两个问题。。。

**Comment by ChenMoGe2** [comment]
谢谢您，确实是大小写的问题，百度搜索ip确实变化了，另外还有两个问题
1.使用我自己开发的tcp和udp测试demo在服务器上读取ip并没有变化，这个使用shadowrocket是可以变化的，是不是我这边的配置还忽略了其他的地方
2.咱们这个项目有办法指定进程进行代理吗

**Comment by eycorsican** [comment]
1. 没看懂你在说什么
2. iOS 不可能做到指定进程，指定USER-AGENT倒是很容易做

**Comment by ChenMoGe2** [comment]
1.就是我在浏览器上的http请求走代理了，但是好像socks（tcp和udp包）没有走代理，

**Comment by ChenMoGe2** [comment]
1.就是safari浏览器百度搜ip（http代理）没问题，IP变成ss服务器的ip了。但是socks代理（tcp和udp）好像并没有生效，还是自己wifi下的ip地址。我的目的是想用这个来加速打游戏。
2.好的，我了解了，谢谢您！

**Comment by eycorsican** [comment]
还是没看懂，建议你在桌面运行调试问题看日志

**Comment by ChenMoGe2** [comment]
好的，谢谢您，我自己再看下，辛苦您了
