### ISSUE TITLE
0.2.7版本代理无法成功

### ISSUE THREAD

**Issue by WifiFly** [eycorsican/ileaf#13]

**Comment by eycorsican** [comment]
HTTP inbound 好像的确没法在ios上用了，没具体看什么原因，用nc连接是没问题的

**Comment by eycorsican** [comment]
但你可以只用 TUN，不开 HTTP

**Comment by 616115891** [comment]
> 但你可以只用 TUN，不开 HTTP

你好,现在很容易no route to host
