### ISSUE TITLE
您好，关于geo.mmdb 配置的问题

### ISSUE THREAD

**Issue by izhangbowen** [eycorsican/ileaf#14]
您好，请问您这个框架 geo.mmdb 怎么配置，小白看了几遍文档没看懂

**Comment by eycorsican** [comment]
https://github.com/eycorsican/leaf/blob/master/README.zh.md#mmdb

在ios上，简单点就是直接把geo.mmdb文件添加到[NetworkExtension项目目录](https://github.com/eycorsican/ileaf/tree/main/PacketTunnel)下，这个目录就是NetworkExtension的可执行文件的所在目录。

配置就不需要指定geo.mmdb的路径：
```ini
# 等效于 EXTERNAL, mmdb:us, Fallback
GEOIP, us, Fallback

# 执行文件目录当中必需有 `geo.mmdb` 文件
EXTERNAL, mmdb:us, Fallback
```

**Comment by izhangbowen** [comment]
OK，多谢
