### ISSUE TITLE
【问题】关于Shadowsocks配置加密

### ISSUE THREAD

**Issue by izhangbowen** [eycorsican/ileaf#15]
我看您给的testflight的demo里面支持的加密方式只有三种：
- chacha20-ietf-poly1305
- aes-128-gcm
- aes-256-gcm

现在是否支持其他的加密方式？比如aes-256-cfb这种加密方式

**Comment by eycorsican** [comment]
只有AEAD，你想要Stream Cipher可以自己加：https://github.com/eycorsican/leaf/blob/master/leaf/src/common/crypto.rs
