### ISSUE TITLE
show client ip

### ISSUE THREAD

**Issue by zzw169** [eycorsican/ileaf#2]
when I use this demo, and visit the cn web , it show the real client ip. how to change it to server's ip. thanks

**Comment by eycorsican** [comment]
Proxy requests are controlled by rules, removing this line should meet your needs.

https://github.com/eycorsican/ileaf/blob/8ce9748601ef6abbef85d7f699a26d797c7fb232/PacketTunnel/PacketTunnelProvider.swift#L16

**Comment by elsadeny** [comment]
How can I run v2mess and websocket in the app?
