### ISSUE TITLE
[问题]您好，如何 build  iOS 端使用的库

### ISSUE THREAD

**Issue by iMattZ** [eycorsican/ileaf#20]
我尝试使用 cargo build -p leaf-mobile 进行编译

error[E0432]: unresolved imports `super::ios::asl_log`, `super::ios::ASL_LEVEL_NOTICE`
  --> leaf-mobile/src/logger.rs:10:18
   |
10 | use super::ios::{asl_log, ASL_LEVEL_NOTICE};
   |                  ^^^^^^^  ^^^^^^^^^^^^^^^^ no `ASL_LEVEL_NOTICE` in `ios`
   |                  |
   |                  no `asl_log` in `ios`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: could not compile `leaf-mobile`

**Comment by eycorsican** [comment]
https://github.com/eycorsican/leaf/blob/173b8adde1935a4503639f37f720da7ad482ec8e/.github/workflows/release.yml#L135-L145
