### ISSUE TITLE
【iOS】Trojan-go模式 在 进行测速的时候会自动断开VPN

### ISSUE THREAD

**Issue by iMattZ** [eycorsican/ileaf#23]
您好，我使用的Trojan-go模式，建立VPN后在进行VPN测速的时候VPN会自动断开，在非测速情况下使用正常
设备： XR
系统：14.2
同时使用Shadowwrocket（小飞机）进行测试，没有出现类似问题

**Comment by AnhTVc** [comment]
can you share conf?

**Comment by WifiFly** [comment]
> can you share conf?
Do you have a telegram?

**Comment by WifiFly** [comment]
> can you share conf?

I want to talk to you about leaf

**Comment by shizong888** [comment]
@eycorsican Is there any solution for this issue? I also have the same issue with both trojan-go and trojan-gfw connections, wondering if there's any way to resolve the issue.
