### ISSUE TITLE
问题：建立SS连接后，会立即断开

### ISSUE THREAD

**Issue by iMattZ** [eycorsican/ileaf#24]
![image](https://user-images.githubusercontent.com/20237638/104169726-f7f81880-543a-11eb-9ff7-55c867404d88.png)

点击连接，出现vpn标志后，会立即关闭
打断点，停在了run_leaf() 这个函数上
项目里面现在包含了patotso的代码，是否有影响
请帮忙看一下

下面是加载调用栈信息
![image](https://user-images.githubusercontent.com/20237638/104178862-f5e78700-5445-11eb-847f-cc2f7d3e5e1d.png)

**Comment by eycorsican** [comment]
看看日志或许能给到更多信息

**Comment by iMattZ** [comment]
你说的日志是xcode控制台输出的日志吗？ @eycorsican

**Comment by iMattZ** [comment]
> 看看日志或许能给到更多信息

你说的日志是xcode控制台输出的日志吗？

**Comment by eycorsican** [comment]
leaf 的日志。

你下一个问题不会是要问怎么看 leaf 的日志吧？我可不会继续回答，你需要自己做点功课，自己学会调试，不然这基础问题没完没了，我也不建议你继续用这个了，leaf 没完善到这程度。

**Comment by iMattZ** [comment]
👌
