### ISSUE TITLE
你好,请问下游戏网络能代理吗?

### ISSUE THREAD

**Issue by no-bibi** [eycorsican/ileaf#25]
你好,我使用trojan-go 作为服务器,用ileaf做客户端,目前网页和常用APP能够正常走代理.
但是,我想使用ileaf顺便把游戏网络也代理了,请问是否支持?
PS:trojan-go 支持做游戏代理

**Comment by eycorsican** [comment]
代理网页和代理游戏有什么本质区别吗？

**Comment by no-bibi** [comment]
> 代理网页和代理游戏有什么本质区别吗？

在server角度来看,是没有区别的.不过客户端要支持才行

以下是我使用testflight的ileaf客户端,填写的配置文件

[General]
dns-server = 114.114.114.114, 223.5.5.5
always-real-ip = apple.com
socks-interface = 127.0.0.1
socks-port = 3080

[Proxy]
jf = trojan, 192.168.50.82, 443, password=123456, sni=test.mysite.com

**为了方便调试,我把trojan服务器搭建在局域网,手机也在这局域网中.**




目前出现的情况是:
-  网页和常用的app,比如淘宝,京东 都可以正常代理,server 端控制台可以看到链接信息.
-  和平精英等游戏,在大厅都是正常代理,但是在开始游戏时,**会卡在载入阶段**

如果我使用的是Android的v2rayNG ,就可以正常开始游戏.

为了确保v2rayNG是成功代理了游戏网络,我特意做了以下测试

- trojan 服务器关闭,那么和平精英会立刻断掉链接
- trojan 服务器开启,和平精英会立刻重连,并且正常进行

手机:iphone8 plus ios14.1
ileaf:testfight 1.0(7)
trojan-go: v0.8.2 
trojan-go运行环境:Macos 10.15.7

非常欣赏你的leaf项目,望回复 :)

**Comment by eycorsican** [comment]
试试把这行
```ini
always-real-ip = apple.com
```
改为
```ini
always-real-ip = *
```
我不太确定testflight支不支持这个设置，不行你再告诉我更新下

**Comment by no-bibi** [comment]
> 试试把这行
> 
> ```ini
> always-real-ip = apple.com
> ```
> 
> 改为
> 
> ```ini
> always-real-ip = *
> ```
> 
> 我不太确定testflight支不支持这个设置，不行你再告诉我更新下


太厉害了，搞定了~
