### ISSUE TITLE
SSL-verify how to set false

### ISSUE THREAD

**Issue by abwizeline** [eycorsican/ileaf#29]
Trojan supports this option for ssl verification:

ssl:{
  verify: false
}

Can't find similar option in config in iLeaf

**Comment by abwizeline** [comment]
UP, appreciate for help. I am using Igniter trojan vpn

**Comment by eycorsican** [comment]
This feature is not formally supported in leaf, but it's almost done, I just don't want to enable it: https://github.com/eycorsican/leaf/blob/master/leaf/src/proxy/tls/stream.rs

Perhaps you could make your own fork.

**Comment by abwizeline** [comment]
@eycorsican Thanks for your answer. Yes i seen your code already, will investigate on my side
