### ISSUE TITLE
ios13.0之前的版本不能连接

### ISSUE THREAD

**Issue by fbenpao** [eycorsican/ileaf#3]
你好，ios13.0之前的版本不能连接这个问题怎么解决，ios版本12.6，xcode11.5

**Comment by eycorsican** [comment]
There was such an issue in leaf, but it's already fixed in https://github.com/eycorsican/leaf/commit/2e8b16a452853eb2c54907675323c96060d9ef30

**Comment by fbenpao** [comment]
我在ileaf demo里用的是Release v0.2.4的库，仍然出现这个不能连接的问题（ios版本12.6）

**Comment by eycorsican** [comment]
I can confirm the latest release works on iOS 12.4.8, it doesn't seem an issue related to the iOS version.

**Comment by fbenpao** [comment]
不能连接应该和版本无关，于是我把日志打印了出来，摘抄如下：Nov 11 09:40:41 nesessionmanager(NetworkExtension)[117] <Error>: SIOCGIFMTU failed: Device not configured
Nov 11 09:40:41 nesessionmanager(NetworkExtension)[117] <Error>: NEVirtualInterfaceAdjustReadBufferSize: interface_get_mtu failed (6), defaulting to max mtu，

**Comment by eycorsican** [comment]
Closing as there isn't enough information to show this is an issue in leaf.

**Comment by fbenpao** [comment]
我已经解决了，谢谢，你在做一件伟大的事情

**Comment by fbenpao** [comment]
我已经解决了，谢谢，你在做一件伟大的事情
