### ISSUE TITLE
能否关闭UDP代理功能

### ISSUE THREAD

**Issue by never-afk** [eycorsican/ileaf#31]
场景:开启代理后,玩游戏会导致卡在进入游戏的进度条上

期望效果,只代理网页和常用APP(京东,淘宝)网络,不代理游戏相关的UDP转发功能
尝试过修改成http代理模式,但是好像http inbound在IOS并未启用?
```
interface = 127.0.0.1
port = 1087
```

目前我看到的是ios的inbound 好像只能是 'tun inbound' 的模式.
这种虚拟网卡转发成packet的办法,好像会把udp也给代理了.

是否有相应的办法,达到看YouTube和玩游戏互不影响?

通过[RULE]配置ip,domain规则,感觉不是一劳永逸的办法?

**Comment by eycorsican** [comment]
http inbound 对应 ios 的 httpsServer 设置。另外最新版本修复了些 UDP 问题你可以试试。
