### ISSUE TITLE
问大佬一个windows端使用leaf的问题

### ISSUE THREAD

**Issue by ChenMoGe2** [eycorsican/ileaf#37]
作者你好，由于在leaf项目下没有找到issues区，故在此提问
windows端使用leaf这个可以像go-tun2socks一样区分进程名吗，我看了leaf的文档没有找到相关的设置
谢谢指教

**Comment by eycorsican** [comment]
不支持的

**Comment by ChenMoGe2** [comment]
> 不支持的

好的，谢谢
