### ISSUE TITLE
请教大佬一个问题 VPN 配置里显示需要更新这个是什么原因造成的那

### ISSUE THREAD

**Issue by weweMM** [eycorsican/ileaf#39]
截图如下  机型 是  8Plus  14.2  
![WechatIMG1](https://user-images.githubusercontent.com/23069769/110753174-36feea80-8281-11eb-88a1-a2871c6b3569.jpeg)

**Comment by eycorsican** [comment]
没遇过，你点进去删掉试试呗

**Comment by weweMM** [comment]
删掉VPN 重新安装都试过 不太好用

**Comment by eycorsican** [comment]
好像跟Xcode里设置的iOS deployment target有关

**Comment by weweMM** [comment]
有两个手机  一个12 一个 8plus   同样的环境 12一直都没出现这个问题   8plus 出现了  
那我就在从头检查下

**Comment by weweMM** [comment]
解决了  改变了build 号  或者版本号就可以了
