### ISSUE TITLE
WebSocket protocol error

### ISSUE THREAD

**Issue by kittycalloway** [eycorsican/ileaf#5]
Hi,

My websocket code works perfectly with go-tun2socks tho it does have high memory consumption issue.

Now I am trying to compile my websocket code to work with ileaf instead, and I have encountered an issue seemingly related to a limit.

tcp link 240.0.0.1:64202 <-> oauthaccountmanager.googleapis.com:443 interrupted: downlink error: ws error: WebSocket protocol error: Connection reset without closing handshake
pick route failed: no matching rules
picked default route [SocksOut_chain] for 240.0.0.1:57426 -> redirector.googlevideo.com:443

Symptons: works fine for the first few seconds then these errors come up.

I was wondering whether you have tested if ileaf works properly with socks + websocket?  Plain socks works properly. Vmess + ws works too, whereas socks + ws doesn't. DM you on Twitter/ Email sent already, looking forward to your reply.

Thx

**Comment by eycorsican** [comment]
There's indeed an issue in the socks outbound related to protocol chaining:

https://github.com/eycorsican/leaf/blob/1be23bc85d596d213ec05a003ab898c5623feea9/leaf/src/proxy/socks/outbound/udp.rs#L49

I'm not going to fix this for the moment as I don't see this an essential feature, I suggest you try your hand at this issue.

**Comment by kittycalloway** [comment]
> There's indeed an issue in the socks outbound related to protocol chaining:
> 
> https://github.com/eycorsican/leaf/blob/1be23bc85d596d213ec05a003ab898c5623feea9/leaf/src/proxy/socks/outbound/udp.rs#L49
> 
> I'm not going to fix this for the moment as I don't see this an essential feature, I suggest you try your hand at this issue.

Thanks for your reply. 

It is an essential feature, at least to us. Well, just made a foray into Rust and not good at it. 

We r willing to pay if u can fulfill this feature shortly. Reply to my gmail if u r interested. 

Thanks again

**Comment by eycorsican** [comment]
1. It's not clear whether the issue I mentioned above is the one you're encountering as you provide very limited information.

2. Streaming SOCKS UDP packets on WS is barely a right design as there's no boundary between consecutive packets, only DNS queries may work because both the request and response are single packets

**Comment by kittycalloway** [comment]
> 1. It's not clear whether the issue I mentioned above is the one you're encountering as you provide very limited information.
> 2. Streaming SOCKS UDP packets on WS is barely a right design as there's no boundary between consecutive packets, only DNS queries may work because both the request and response are single packets

1. I am not sure if that is the cause of the websocket protocol error, we r building direct udp version to test.

2. In our case, we dont rly need to stream SOCKS UDP packets. We can disable them and reply to DNS queries with a truncate flag which will force it to requery with TCP DNS.

3. Would you mind if we create a group chat on Telegram so you could help us locate the issue as paid consultancy service in a more straightforward way. @me1on   we do 24/7 service ))

**Comment by kittycalloway** [comment]
Fixed. 
Direct UDP version works even tho there is some log info 
dispatch udp 240.0.0.1:54925 -> 173.255.0.168:8080 to [ws_socks_out] failed: invalid chain
Gonna code a UDP redirector/UDP Stub for UDP DNS to UDP TCP and drop other UDP packets.

Thanks
