### ISSUE TITLE
Hey, How to fix this error? 

### ISSUE THREAD

**Issue by fuqiangleon** [eycorsican/ileaf#51]
![image](https://user-images.githubusercontent.com/1288399/119699438-c1201d80-be84-11eb-87a7-3c10b5293a32.png)

**Comment by giftedunicorn** [comment]
The name is changed to leaf_run and leaf_shutdown

**Comment by fuqiangleon** [comment]
![image](https://user-images.githubusercontent.com/1288399/119750196-61009a00-becb-11eb-919c-2039f2a3366a.png)

Did I miss something?
