### ISSUE TITLE
Can't access foreign websites

### ISSUE THREAD

**Issue by xiaofeiji-ui** [eycorsican/ileaf#55]
My Config

`[General]
loglevel = trace
dns-server = 202.252.144.228,202.151.69.65,217.79.16.148,119.29.29.29,208.67.222.222,8.8.8.8,8.8.4.4,223.5.5.5, 114.114.114.114,202.238.95.24,202.12.27.33,209.166.160.36
tun-fd = REPLACE-ME-WITH-THE-FD
routing-domain-resolve = true

interface = 127.0.0.1
port = 1087

socks-interface = 127.0.0.1
socks-port = 1086

[Proxy]
Direct = direct
VMess = vmess, 服务器地址, 端口,username=用户id,uuid=用户id
[Rule]
FINAL, Proxy

[On Demand]
CONNECT`

My NEPacketTunnelNetworkSettings

`let newSettings = NEPacketTunnelNetworkSettings(tunnelRemoteAddress: 服务器ip)
        newSettings.ipv4Settings = NEIPv4Settings(addresses: [服务器ip], subnetMasks: ["255.255.255.0","255.255.255.252"])
        newSettings.ipv4Settings?.includedRoutes = [NEIPv4Route.`default`()]
        let proxySettings = NEProxySettings()
        
        let httpsServer = NEProxyServer(address: 服务器ip, port: Int(服务器端口))
        proxySettings.httpsEnabled = false
        let httpServer = NEProxyServer(address: 服务器ip, port: Int(服务器端口))
        proxySettings.httpEnabled = false
        httpsServer.authenticationRequired = false
        proxySettings.matchDomains = [""]
        proxySettings.excludeSimpleHostnames = true
        proxySettings.httpsServer = httpsServer
        proxySettings.httpServer = httpServer;
        newSettings.proxySettings = proxySettings
           
        
        newSettings.dnsSettings = NEDNSSettings(servers: ["8.8.8.8","8.8.4.4","223.5.5.5", "114.114.114.114","202.238.95.24","202.12.27.33"])
        newSettings.mtu = 1500
        return newSettings`

NEVPNStatusDidChange  显示是.contented

can you help me?

**Comment by alsojin0806** [comment]
规则写错了 请仔细看教程

**Comment by xiaofeiji-ui** [comment]
> 规则写错了请仔细看教程

应该怎么修改呢！

**Comment by alsojin0806** [comment]
https://github.com/eycorsican/ileaf/blob/main/PacketTunnel/PacketTunnelProvider.swift#L15

**Comment by xiaofeiji-ui** [comment]
> [https://github.com/eycorsican/ileaf/blob/main/PacketTunnel/PacketTunnelProvider.swift#L15 ](https://github.com/eycorsican/ileaf/blob/main/PacketTunnel/PacketTunnelProvider.swift#L15)
> https://github.com/eycorsican/ileaf/blob/main/PacketTunnel/PacketTunnelProvider.swift#L19
> 看看他们行，各种尝试

`[General]
loglevel = trace
dns-server = 223.5.5.5, 114.114.114.114
tun-fd = REPLACE-ME-WITH-THE-FD
routing-domain-resolve = true

# Local HTTP CONNECT proxy
interface = 127.0.0.1
port = 1087

# Local SOCKS5 proxy with UDP Associate support
socks-interface = 127.0.0.1
socks-port = 1086

[Proxy]
Direct = direct

VMessWSS = vmess, 地址, 端口, username=用户id, ws=true, tls=true, ws-path=/ws
[Rule]
EXTERNAL, site:cn, Direct
EXTERNAL, mmdb:cn, Direct
FINAL, Proxy`

我看都一样呀。我们需要用vmess协议

**Comment by alsojin0806** [comment]
FINAL, Proxy  改成 FINAL, VMessWSS  試試看

**Comment by xiaofeiji-ui** [comment]
> FINAL, VMessWSS

默认	19:19:43.985287+0800	MyPacketTunnel	\^[[37m[2021-06-06 19:19:43][\^[[37mDEBUG\^[[0m\^[[37m] dispatch tcp 服务器ip:51484 -> m.facebook.com:443 to [Direct] failed: all attempts failed, last error: timed out\^[[0m  这是日志 ；安卓这个节点是可以连接的。

**Comment by xiaofeiji-ui** [comment]
> FINAL, Proxy改成FINAL, VMessWSS 学习看

thank you very much.I succeeded
