### ISSUE TITLE
iOS15无法正常创建连接，14正常！

### ISSUE THREAD

**Issue by ponyChang** [eycorsican/ileaf#59]
文件：PacketTunnel/PacketTunnelProvider.swift 中的该语句报错：

let tunFd = self?.packetFlow.value(forKeyPath: "socket.fileDescriptor") as! Int32

不知是不是iOS15不再支持这种获取fileDescriptor的方式。

**Comment by giftedunicorn** [comment]
我也遇到了这个问题，还有其他办法获得 tunfd 吗？

**Comment by ponyChang** [comment]
@giftedunicorn 我也不清楚！只查到了苹果开发者论坛里，关于socket.fileDescriptor的讨论：

https://developer.apple.com/forums/thread/13503

**Comment by azhm** [comment]
if #available(iOS 15, *) {
      var buf = [CChar](repeating: 0, count: Int(IFNAMSIZ))
      let utunPrefix = "utun".utf8CString.dropLast()

      return (0...1024).first { (_ fd: Int32) -> Bool in
          var len = socklen_t(buf.count)
          return getsockopt(fd, 2, 2, &buf, &len) == 0 && buf.starts(with: utunPrefix)
      }
  } else {
      return self.packetFlow.value(forKeyPath: "socket.fileDescriptor") as? Int32
  }

@giftedunicorn @ponyChang

**Comment by zx2c4** [comment]
You mean this: https://git.zx2c4.com/wireguard-apple/commit/?id=9777f51ba28734ed8043eafc77a667d1050f5b5a

**Comment by ponyChang** [comment]
That's awesome, it's working on iOS 15!
Thanks everyone, now I can close my issue.
