### ISSUE TITLE
Main page has only one button

### ISSUE THREAD

**Issue by elsadeny** [eycorsican/ileaf#6]
Is this how it is supposed to run? or there is something am doing wrong?

This the main entry and is somehow empty, please help

![image](https://user-images.githubusercontent.com/29357454/100038146-73c3e480-2e3e-11eb-8bf7-ce6c9275c89b.png)

**Comment by eycorsican** [comment]
Yes, that's it, all you need is a start button.

The configuration is hard coded and can be changed here
https://github.com/eycorsican/ileaf/blob/8ce9748601ef6abbef85d7f699a26d797c7fb232/PacketTunnel/PacketTunnelProvider.swift#L5

For config samples you can find one here
https://github.com/eycorsican/leaf/blob/master/README.zh.md#conf

**Comment by elsadeny** [comment]
when I connect it automatically disconnect, is anything else I need to change? cause no output error
