### ISSUE TITLE
  "_run_leaf", referenced from:

### ISSUE THREAD

**Issue by aishuidedabai** [eycorsican/ileaf#7]
"_run_leaf", referenced from:
      closure #1 () -> () in closure #1 (Swift.Error?) -> () in PacketTunnel.PacketTunnelProvider.startTunnel(options: [Swift.String : __C.NSObject]?, completionHandler: (Swift.Error?) -> ()) -> () in PacketTunnelProvider.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by eycorsican** [comment]
https://github.com/eycorsican/ileaf/issues/1#issuecomment-723416595
